# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Finance-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


	pod 'IQKeyboardManagerSwift'
	pod 'Charts', '3.5.0'


  # Pods for Finance-app

end
